name = "Project"
version = "0.1.0"
defaultTargets = ["Project"]

[[require]]
name = "CodeLib"
git = "https://github.com/cajal-technologies/talos"
subDir = "codelib"
rev = "main"

[[lean_lib]]
name = "Project"
