name = "Project"
version = "0.1.0"
defaultTargets = ["Project"]

[[require]]
name = "CodeLib"
git = "https://github.com/cajal-technologies/talos"
subDir = "codelib"
rev = "3d742fbe59f4238b9bfc60ad54c155ed0814ae57"

[[lean_lib]]
name = "Project"
